name: python3
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.19.0.post1
  - cmocean=2.0
  - geoviews
  - jupyterlab=3.0.16
  - jupyter-panel-proxy
  - numpy=1.21.0
  - pandas=1.3.0
  - panel
  - param
  - pip=21.1.3
  - python=3.9.6
  - xarray=0.18.2
  - pip:
    - netcdf4==1.5.7
    - seaborn==0.11.1